### ISSUE TITLE
README.md example does not compile

### ISSUE THREAD

**Issue by jwmurray** [e1r0nd/voca_rs#16]
When I compile
In the README.md, when compiling:

   let snake_string = case::snake_case(chop::slice(&words_in_string, 13, 28));

rustc reports that slice() is returning a Strong and that snake_case() must take a &str.

I rewrote this as

   let snake_string = case::snake_case(&*chop::slice(&words_in_string, 13, 28));

and it worked.

**Comment by e1r0nd** [comment]
Nice catch! Thank you!
Fixed https://github.com/e1r0nd/voca_rs/commit/3fa42a11388285a23f5c3a7d52bfa326a4433b2a
