### ISSUE TITLE
split::words alternative that keeps punctuation

### ISSUE THREAD

**Issue by SirWindfield** [e1r0nd/voca_rs#19]
I currently have to singularise whole sentences. The code that I came up with splits a string using `voca_rs::split::words` and maps each word using `inflector::string::singularize::to_singular`. I then stitch it back together using `Vec#join(" ")`.

This does remove punctuation like `,` and `.` though. It would be great if there was a method that keeps the punctuation intact. I saw that you wanted to add support for inflector. Did you already have an idea on how to handle this specific case here?

**Comment by e1r0nd** [comment]
Do you really need `voca` in this case? Doesn't `split_whitespace` work for you?

```rust
let s = "Some sort, of a - sentence."
        .split_whitespace()
        .collect::<Vec<&str>>();
assert_eq!(s, ["Some", "sort,", "of", "a", "-", "sentence."]);
```

**Comment by SirWindfield** [comment]
It does in almost all the cases. But I do have similar input to the one you showcased for `split::words` like `XmlHttpRequest`. Maybe I have to put something custom made together!

**Comment by e1r0nd** [comment]
Could you please provide a test case to review, so I'd be able to think about the solution?

**Comment by e1r0nd** [comment]
@SirWindfield Please consider the following code snippet, whether this solution works for you?
```rust
let s = "Some sort, of a - sentence using LazyLoad with XMLHttpRequest."
    .split_whitespace()
    .collect::<Vec<_>>();
let mut res = Vec::new();
for w in s {
    if w._words().len() > 1 {
        let vec = w._words();
        for v in vec {
            res.push(v);
        }
    } else {
        res.push(w);
    };
}
assert_eq!(
    res,
    [
        "Some", "sort,", "of", "a", "-", "sentence", "using", "Lazy", "Load", "with", "XML",
        "Http", "Request"
    ]
);
```
Please note that it drops the last point because of `words()` function behavior; you need to cover such edge cases.

Another possible solution is to cut out the `split::words` function and to rewrite it for your needs.

**Comment by e1r0nd** [comment]
Closed as it's stalled (workaround has been proposed).
